github: [metadata]
kramdown:
   input: GFM
   hard_wrap: false
gems:
   - jekyll-coffeescript
   - jekyll-paginate
lsi: false
safe: true
source: index.md
incremental: false
highlighter: rouge
gist:
   noscript: false
kramdown:
   math_engine: mathjax
   
---
title: The Title
layout: post
---

Here is my page.
