# Dependencies
markdown: kramdown
highlighter: rouge

kramdown:
  auto_ids: true

# Permalinks
permalink: pretty

# Gems
gems:
  - jekyll-paginate

# Setup
name:           My Blog
description:    Official blog for Tieantono.
url:            http://Tieantono.github.io

paginate:       5
encoding:       UTF-8
future:         true

exclude:        ["README.md"]

# Links
blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com
themes:           http://themes.getbootstrap.com

# Social
title: My Blog
description: This is my blog.
